# Generated by Django 4.2.6 on 2024-01-03 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('bKind', models.CharField(choices=[('سكني', 'سكني'), ('تجاري', 'تجاري'), ('سكني وتجاري', 'سكني وتجاري')], max_length=50, verbose_name='نوع المبنى')),
                ('dName', models.CharField(blank=True, max_length=50, verbose_name=' اسم العقار في الصك ')),
                ('dID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='رقم الصك ')),
                ('dDate', models.DateField(blank=True, null=True, verbose_name='تاريخ الصك')),
                ('bName', models.CharField(max_length=50, verbose_name=' اسم المبنى ')),
                ('bAddress', models.CharField(blank=True, max_length=50, verbose_name='عنوان المبنى')),
                ('bNote', models.TextField(blank=True, max_length=500, verbose_name='ملاحظة ')),
                ('dImage', models.FileField(blank=True, upload_to='Idphotos/%y/%m/%d', verbose_name='صورة الصك ')),
                ('bimage', models.FileField(blank=True, upload_to='Idphotos/%y/%m/%d', verbose_name='صورة المبنى ')),
            ],
            options={
                'verbose_name': 'المباني',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_kind', models.CharField(choices=[('تجاري', 'تجاري'), ('سكني', 'سكني')], max_length=50, verbose_name='سكني ام تجاري')),
                ('contractNumber', models.BigIntegerField(max_length=50, verbose_name='رقم العقد الالكتروني')),
                ('startDate', models.DateField(verbose_name='تاريخ البدء')),
                ('endDate', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الإيجارية لكامل العقد')),
                ('cFile', models.FileField(blank=True, upload_to='contract/%y/%m/%d', verbose_name='العقد  ')),
                ('cNote', models.TextField(blank=True, max_length=500, verbose_name='ملاحظة ')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ckind', models.CharField(choices=[('فرد', 'فرد'), ('مؤسسة', 'مؤسسة')], max_length=50, verbose_name='نوع المستأجر')),
                ('cID', models.BigIntegerField(verbose_name='رقم الاثبات')),
                ('cDob', models.DateField(verbose_name='تاريخ الميلاد')),
                ('cName', models.CharField(max_length=50, verbose_name='اسم المستأجر')),
                ('cNumber', models.BigIntegerField(max_length=10, verbose_name='رقم المستأجر')),
                ('cIdImage', models.ImageField(blank=True, upload_to='Idphotos/%y/%m/%d', verbose_name='صورة الاثبات')),
            ],
            options={
                'verbose_name': 'المستأجرين',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_due', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='myejar.contracts')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('uKind', models.CharField(choices=[('تجاري', 'تجاري'), ('سكني', 'سكني'), ('سكني وتجاري', 'سكني وتجاري')], max_length=50, verbose_name='سكني ام تجاري')),
                ('uKind2', models.CharField(choices=[('شقة', 'شقة'), ('محل', 'محل'), ('دور ', 'دور '), ('عمارة ', 'عمارة '), ('فندق ', 'فندق '), ('أخرى ', 'أخرى ')], max_length=50, verbose_name='نوع الوحدة  ')),
                ('uName', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name=' اسم الوحدة ')),
                ('uNumber', models.IntegerField(max_length=10, verbose_name='رقم الوحدة - يجب ان يكون رقم خاص للوحدة ')),
                ('uRoomsNo', models.IntegerField(blank=True, max_length=10, verbose_name=' عدد الغرف ')),
                ('uFloor', models.IntegerField(blank=True, max_length=10, verbose_name='الدور  ')),
                ('uElectricity', models.BigIntegerField(blank=True, max_length=10, null=True, verbose_name='رقم سداد الكهرباء  ')),
                ('uWater', models.BigIntegerField(blank=True, max_length=10, null=True, verbose_name=' رقم سداد المياه ')),
                ('building', models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='myejar.buildings', verbose_name='المبنى  ')),
            ],
            options={
                'verbose_name': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='Payment_recived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('حواله', 'حواله'), ('كاش', 'كاش'), ('شيك', 'شيك'), ('أخرى', 'أخرى')], max_length=50, null=True, verbose_name='طريقة السداد  ')),
                ('doc_number', models.CharField(max_length=50, unique=True, verbose_name='بيانات المستند  ')),
                ('payment', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_received', to='myejar.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=80, verbose_name='اسم المستلم')),
                ('bNumber', models.BigIntegerField(max_length=10, verbose_name='رقم الجوال ')),
                ('eamount', models.IntegerField(max_length=10, verbose_name='المبلغ ')),
                ('eamounttext', models.CharField(blank=True, max_length=100, verbose_name='المبلغ كتابة ')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='مقابل ')),
                ('eDb', models.DateField(verbose_name='تاريخ الصرف')),
                ('eBuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myejar.buildings', verbose_name='المبنى  ')),
            ],
            options={
                'verbose_name': 'المصروفات',
            },
        ),
        migrations.AddField(
            model_name='contracts',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='myejar.customers', verbose_name='المستأجر'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='unit',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='myejar.units', verbose_name='الوحدة'),
        ),
    ]
