# Generated by Django 4.2.6 on 2023-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='uElectricity',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='رقم سداد الكهرباء  '),
        ),
        migrations.AlterField(
            model_name='units',
            name='uWater',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name=' رقم سداد المياه '),
        ),
    ]
