# Generated by Django 4.2.6 on 2024-01-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cDob',
            field=models.DateField(blank=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cID',
            field=models.BigIntegerField(blank=True, verbose_name='رقم الاثبات'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cNumber',
            field=models.BigIntegerField(blank=True, max_length=10, verbose_name='رقم المستأجر'),
        ),
    ]
