# Generated by Django 4.2.6 on 2024-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contractNumber',
            field=models.BigIntegerField(max_length=50, verbose_name='رقم العقد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cID',
            field=models.BigIntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='رقم الاثبات'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cNumber',
            field=models.BigIntegerField(max_length=10, verbose_name='رقم المستأجر'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bNumber',
            field=models.BigIntegerField(max_length=10, verbose_name='رقم الجوال '),
        ),
        migrations.AlterField(
            model_name='units',
            name='uElectricity',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, verbose_name='رقم سداد الكهرباء  '),
        ),
        migrations.AlterField(
            model_name='units',
            name='uWater',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, verbose_name=' رقم سداد المياه '),
        ),
    ]
