# Generated by Django 4.2.6 on 2024-01-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0002_alter_customers_cdob_alter_customers_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cDob',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cID',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='رقم الاثبات'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cNumber',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, verbose_name='رقم المستأجر'),
        ),
        migrations.AlterField(
            model_name='units',
            name='uFloor',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='الدور  '),
        ),
        migrations.AlterField(
            model_name='units',
            name='uKind',
            field=models.CharField(blank=True, choices=[('تجاري', 'تجاري'), ('سكني', 'سكني'), ('سكني وتجاري', 'سكني وتجاري')], max_length=50, null=True, verbose_name='سكني ام تجاري'),
        ),
        migrations.AlterField(
            model_name='units',
            name='uKind2',
            field=models.CharField(blank=True, choices=[('شقة', 'شقة'), ('محل', 'محل'), ('دور ', 'دور '), ('عمارة ', 'عمارة '), ('فندق ', 'فندق '), ('أخرى ', 'أخرى ')], max_length=50, null=True, verbose_name='نوع الوحدة  '),
        ),
        migrations.AlterField(
            model_name='units',
            name='uNumber',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='رقم الوحدة - يجب ان يكون رقم خاص للوحدة '),
        ),
        migrations.AlterField(
            model_name='units',
            name='uRoomsNo',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name=' عدد الغرف '),
        ),
    ]
