# Generated by Django 4.2.6 on 2024-01-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0002_remove_customers_id_alter_contracts_contractnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='cID',
            field=models.BigIntegerField(max_length=10, verbose_name='رقم الاثبات'),
        ),
    ]
