# Generated by Django 4.2.6 on 2024-01-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0003_customers_id_alter_customers_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
