# Generated by Django 4.2.6 on 2024-01-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0003_alter_customers_cdob_alter_customers_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='uNumber',
            field=models.CharField(max_length=10, verbose_name='رقم الوحدة - يجب ان يكون رقم خاص للوحدة '),
        ),
    ]
