# Generated by Django 4.2.6 on 2024-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0004_alter_customers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cID',
            field=models.BigIntegerField(verbose_name='رقم الاثبات'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cIdImage',
            field=models.ImageField(blank=True, upload_to='Idphotos/%y/%m/%d', verbose_name='صورة الاثبات'),
        ),
    ]
