# Generated by Django 4.2.6 on 2024-01-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0004_alter_units_unumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='uNumber',
            field=models.CharField(verbose_name='رقم الوحدة - يجب ان يكون رقم خاص للوحدة '),
        ),
    ]
