# Generated by Django 4.2.6 on 2024-01-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0005_alter_units_unumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='id',
            field=models.BigAutoField(default='none', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='units',
            name='uName',
            field=models.CharField(max_length=50, verbose_name=' اسم الوحدة '),
        ),
        migrations.AlterField(
            model_name='units',
            name='uNumber',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, verbose_name='رقم الوحدة - يجب ان يكون رقم خاص للوحدة '),
        ),
    ]
