# Generated by Django 4.2.6 on 2024-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0008_alter_units_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='id',
        ),
        migrations.AlterField(
            model_name='units',
            name='uName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name=' اسم الوحدة '),
        ),
        migrations.AlterField(
            model_name='units',
            name='uNumber',
            field=models.BigIntegerField(verbose_name='رقم الوحدة - يجب ان يكون رقم خاص للوحدة '),
        ),
    ]
