# Generated by Django 4.2.6 on 2024-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myejar', '0009_remove_units_id_alter_units_uname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.BigAutoField(default=51656, primary_key=True, serialize=False),
        ),
    ]
